version: '3.7'

services:
    app:
        build: .
        image: verbose-fiesta:${VERSION}
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
        ports:
            - "5000:5000"
